import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'FR' | 'AR' | 'EN' | 'ES';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations: Record<Language, Record<string, string>> = {
  FR: {
    // Header
    'nav.home': 'Accueil',
    'nav.soins': 'Nos Soins',
    'nav.urgences': 'Urgences',
    'nav.conseils': 'Conseils',
    'nav.contact': 'Contact',
    'nav.appointment': 'Prendre RDV',
    'header.location': 'Casablanca, Maroc',
    'header.subtitle': 'Centre Dentaire',
    'header.language': 'Langue',
    
    // Home
    'hero.welcome': 'Bienvenue chez MAPSO',
    'hero.title': 'Votre Sourire, Notre Passion',
    'hero.subtitle': 'Des soins dentaires d\'excellence au cœur de Casablanca',
    'hero.cta': 'Prendre Rendez-vous',
    'hero.call': 'Appeler le cabinet',
    
    'services.title': 'Nos Services',
    'services.subtitle': 'Une gamme complète de soins pour toute la famille',
    'services.details': 'Voir les détails',
    'services.more': 'Savoir Plus',
    
    'service.omni.title': 'Soins Omnipratiques',
    'service.omni.desc': 'Nous réalisons tous les soins d’omnipratique dentaire pour prévenir l’apparition des caries, infections...',
    'service.ortho.title': 'Orthodontie',
    'service.ortho.desc': 'Profitez des soins orthodontiques qui vous aide à rétablir les fonctionnalités et l’esthétique de votre mâchoire.',
    'service.esth.title': 'Soins Esthétiques',
    'service.esth.desc': 'Pour embellir votre sourire, améliorer et restaurer la beauté naturelle de vos dents...',
    'service.paro.title': 'Parodontologie',
    'service.paro.desc': 'Les maladies parodontales sont dues à des infections bactériennes. Découvrez l’ensemble des soins...',
    'service.proth.title': 'Soins Prothétiques',
    'service.proth.desc': 'Vous pouvez remplacer une ou plusieurs dents absentes avec le dispositif dentaire...',
    'service.impl.title': 'Implantologie',
    'service.impl.desc': 'Évitez la fonte osseuse de la mâchoire consécutive à la perte d’une ou plusieurs dents...',

    'features.team.title': 'Equipe Expérimentée',
    'features.team.desc': 'Une équipe professionnelle et homogène à votre service.',
    'features.human.title': 'Approche Humaine',
    'features.human.desc': 'Une approche humaine de la chirurgie dentaire.',
    'features.client.title': 'Service Clientèle',
    'features.client.desc': 'Nous vous accueillons avec joie, nous répondons à toutes vos demandes.',
    'features.covid.title': 'COVID 19',
    'features.covid.desc': 'Mesures mises en place pour vous protéger et pour éviter la propagation du virus.',
    'features.advice.title': 'Conseils',
    'features.advice.desc': 'Nous vous offrons écoute et conseil personnalisé par téléphone.',
    'features.urgency.title': 'Urgences Dentaires',
    'features.urgency.desc': 'Un support sur-mesure pour une prise en charge optimale de vos urgences dentaires.',

    'about.tag': 'À propos de nous',
    'about.title': 'Votre Dentiste de Confiance à Casablanca',
    'about.p1': 'Nos dentistes à Casablanca Maarif pratiquent de nombreuses prestations que le centre offre, tels que : les soins dentaires, l’orthodontie, l’implantologie, la pédodontie mais également à l’amélioration et à la reconstruction de l’esthétique dentaire et du sourire.',
    'about.p2': 'Grâce à des outils à la pointe de la technologie, notre équipe de praticiens est en mesure de réaliser des examens complets et pointieux pour vous garantir le meilleur resultats.',
    'about.cta': 'Mieux nous connaître',

    'quick.urgency.title': 'Urgences Dentaires',
    'quick.urgency.desc': 'Prise en charge immédiate',
    'quick.advice.title': 'Conseils',
    'quick.advice.desc': 'Écoute et accompagnement',
    'quick.find.title': 'Nous Trouver',
    'quick.find.desc': 'Au cœur de Casablanca',

    'cta.title': 'Besoin d\'un renseignement ?',
    'cta.subtitle': 'Notre équipe est à votre disposition pour répondre à toutes vos questions.',

    // Urgences
    'urgences.tag': 'Prise en charge rapide',
    'urgences.title': 'Urgences Dentaires',
    'urgences.intro': 'Accident, infection, ou traumatisme... Les urgences dentaires occasionnent souvent des douleurs vives et nécessitent une intervention rapide.',
    'urgences.availability': 'Disponibilité immédiate',
    'urgences.hours.title': 'AUX HEURES D’OUVERTURE DU CENTRE MAPSO',
    'urgences.hours.desc': 'Nos dentistes expérimentés vous accueillent du lundi au vendredi de 9h00 à 19h00 pour toute urgence.',
    'urgences.hours.note': 'Contactez notre secrétariat pour une prise en charge prioritaire.',
    'urgences.more': 'En savoir plus',
    
    'urgences.pain.title': 'Douleurs Dentaires',
    'urgences.pain.desc': 'Les douleurs dentaires peuvent être insupportables et nécessiter une prise en charge immédiate, notamment en cas d’infection.',
    'urgences.proth.title': 'Urgences Prothétiques',
    'urgences.proth.desc': 'Couronne descellée, appareil cassé ou blessant... La prise en charge rapide est essentielle pour votre confort.',
    'urgences.paro.title': 'Urgences Parodontales',
    'urgences.paro.desc': 'Infections des gencives, de l’os ou des ligaments. Ces pathologies nécessitent une intervention spécialisée.',
    'urgences.trauma.title': 'Urgences Traumatiques',
    'urgences.trauma.desc': 'Traumatismes liés au sport ou aux accidents, particulièrement fréquents chez les enfants.',

    // Conseils
    'conseils.tag': 'Hygiène & Prévention',
    'conseils.title': 'Nos Conseils',
    'conseils.intro1': 'Vous êtes le principal acteur de votre santé bucco-dentaire. L’hygiène est fondamentale pour préserver votre sourire tout au long de votre vie.',
    'conseils.intro2': 'Les experts de MAPSO vous accompagnent dans le choix de vos outils et techniques de brossage.',
    'conseils.expert': "Conseil d'expert",
    'conseils.cta.title': "Besoin d'un bilan complet ?",
    'conseils.cta.desc': 'Prenez rendez-vous pour une consultation de contrôle et recevez des conseils personnalisés.',
    'conseils.cta.btn': 'Prendre rendez-vous',

    'conseils.manual.title': 'La brosse à dents manuelle',
    'conseils.manual.desc': 'Le brossage régulier des dents et l’utilisation du fil dentaire sont indispensables à une bonne santé bucco-dentaire pour prévenir l’apparition de caries.',
    'conseils.mouthwash.title': 'Utilisation du bain de bouche',
    'conseils.mouthwash.desc': 'Pour assurer une bonne hygiène bucco-dentaire, la recommandation essentielle est de vous brosser les dents deux à trois fois par jour.',
    'conseils.electric.title': 'La brosse à dents électrique',
    'conseils.electric.desc': 'Avec une brosse à dents rechargeable, l’action de brossage est très différente car la brosse fournit elle-même le mouvement nécessaire.',
    'conseils.floss.title': 'Utiliser le fil dentaire',
    'conseils.floss.desc': 'Si le brossage fait partie intégrante de la routine, l’utilisation du fil dentaire est un geste essentiel souvent négligé.',

    // Contact
    'contact.tag': 'Contactez-nous',
    'contact.title': 'Parlons de votre sourire',
    'contact.find.title': 'Nous trouver',
    'contact.find.content': "Angle Rue Cadi Iass et Rue Saad Bnou Zarara, Imm EL WASSIA, étg 2, n3 Au dessus de McDonald's, Casablanca 20330",
    'contact.call.title': 'Nous appeler',
    'contact.call.fix': 'Fix',
    'contact.email.title': 'Adresse E-mail',
    'contact.email.desc': 'Envoyez-nous un message',
    'contact.hours.title': 'Horaires Travail',
    'contact.hours.mon_thu': 'Lun - Jeu',
    'contact.hours.fri': 'Ven',
    'contact.hours.sat': 'Sam',
    'contact.form.title': 'Envoyez-nous un message',
    'contact.form.desc': 'Nous vous répondrons dans les plus brefs délais.',
    'contact.form.name': 'Votre nom*',
    'contact.form.name_placeholder': 'Jean Dupont',
    'contact.form.email': 'Votre e-mail*',
    'contact.form.subject': 'Sujet',
    'contact.form.subject_placeholder': 'Demande de renseignement',
    'contact.form.message': 'Votre message*',
    'contact.form.message_placeholder': 'Comment pouvons-nous vous aider ?',
    'contact.form.send': 'Envoyer le message',
    'contact.map.cabinet': 'Notre Cabinet',
    'contact.map.location': 'Casablanca, Maarif',

    // Services
    'services.implant.title': 'Implantologie',
    'services.implant.p1': 'Appelée implantologie orale ou plus simplement implantologie, l’implantologie dentaire est une branche de la chirurgie dentaire pratiquée par votre chirurgien-dentiste et qui consiste à poser des implants dans la mâchoire supérieure (os maxillaire) et/ou dans la mâchoire inférieure (mandibule).',
    'services.implant.p2': 'Cette pose d’implants permettra de remplacer une ou plusieurs dents manquantes et ainsi de remédier à la fois à des problèmes esthétiques, à des problèmes de stabilité de la mâchoire, de mastication et de confort quotidien.',
    'services.implant.p3': 'La pratique chirurgicale de l’implantologie dentaire permet également d’éviter la fonte osseuse de la mâchoire consécutive à la perte d’une ou plusieurs dents quelqu’en soit l’origine (caries, traumatismes, maladie parodontale).',
    'services.implant.pose.title': "La pose d'un implant dentaire",
    'services.implant.pose.desc': 'Un implant dentaire est une racine artificielle, sorte de vis en titane ou en zircone, qu’on va placer dans l’os alvéolaire pour remplacer une ou plusieurs dents absentes.',
    'services.implant.analysis.title': "L'analyse pré-implantaire",
    'services.implant.analysis.desc': 'Avant toute pose d’implants, une analyse pré-implantaire s’impose pour assurer une intervention en toute sécurité et un positionnement optimal.',
    'services.implant.greffe.title': "Greffe osseuse à visée implantaire",
    'services.implant.greffe.desc': "Si le volume osseux n'est pas suffisant, une greffe osseuse sera nécessaire pour assurer la pérennité de l'implant.",
    'services.implant.sinus.title': "Le sinus lift",
    'services.implant.sinus.desc': "Intervention consistant à combler le fond du sinus maxillaire à l'aide d'une greffe osseuse pour permettre la pose d'implants.",
    'services.ortho.title': 'Orthodontie',
    'services.ortho.p1': 'Un sourire esthétique et harmonieux est aujourd’hui un élément important de la vie en société. Si vous êtes complexé(e) par votre sourire, que vous trouvez vos dents mal-alignées ou votre sourire un peu trop gingival, l’orthodontie est une solution simple et efficace pour améliorer grandement votre sourire et votre bien-être. Pour la plupart des gens, l’obtention d’un sourire sain et beau est la principale motivation pour débuter un traitement orthodontique.',
    'services.ortho.p2': 'Pour un enfant, l’enjeu principal est une croissance harmonieuse des mâchoires et un positionnement correct de ses dents pour le prémunir de tout préjudice esthétique ou d’occlusion (la manière dont les deux mâchoires s’articulent) à l’âge adulte.',
    'services.ortho.how_title': 'Comment fonctionne un traitement orthodontique ?',
    'services.ortho.how_desc1': 'Les appareils orthodontiques sont fabriqués en métal, en céramique ou en plastique. Ils peuvent être amovibles ou fixés aux dents par des “bagues”. En exerçant une force douce et constante dans une direction soigneusement contrôlée, les appareils orthodontiques déplacent lentement les dents dans la bonne position.',
    'services.ortho.how_desc2': 'Le temps des appareils exclusivement métalliques est révolu ; vous pouvez maintenant choisir des supports transparents ou métalliques. Aujourd’hui, tout âge est un âge idéal pour porter un appareil dentaire !',
    'services.ortho.duration_title': 'Quelle est la durée d’un traitement orthodontique ?',
    'services.ortho.duration_desc1': 'La durée du traitement varie et peut durer entre un et trois ans, selon plusieurs facteurs, notamment l’âge, la méthode de traitement et l’importance du traitement.',
    'services.ortho.duration_desc2': 'Avant de commencer vos soins orthodontiques, votre orthodontiste discutera de toutes les options thérapeutiques disponibles et vous donnera une estimation de la durée totale de votre traitement.',
    'services.ortho.invisible.title': 'Orthodontie invisible',
    'services.ortho.invisible.desc': 'Il existe de nombreux traitements invisibles d’orthodontie permettant de traiter les malpositions de vos dents avec la plus grande discrétion sans entrevoir une seule seconde que le patient est porteur d’une correction orthodontique !',
    'services.ortho.adult.title': 'Orthodontie adulte',
    'services.ortho.adult.desc': 'Dans le cas de l’orthodontie adulte, le choix de votre traitement sera lié à vos souhaits et besoins, qu\'il s\'agisse d\'un appareil classique ou de solutions plus discrètes.',
    'services.ortho.invisalign.title': 'Invisalign',
    'services.ortho.invisalign.desc': 'Technique utilisant des gouttières transparentes et invisibles fabriquées sur mesure pour aligner les dents de la manière la plus discrète possible.',
    'services.ortho.kids.title': 'Orthodontie enfants et adolescents',
    'services.ortho.kids.desc': 'Dédiée à la prévention et à la correction des anomalies de la dentition pour assurer un bon vieillissement des dents et des gencives.',
    'services.paro.title': 'Parodontologie',
    'services.paro.p1': 'La parodontie est la partie de la dentisterie qui est spécialisée dans le traitement du parodonte, c’est-à-dire les tissus de soutien de la dent : gencive, tissu osseux, cément et ligament parodontal. Les maladies parodontales sont dues à des infections bactériennes.',
    'services.paro.p2': 'Découvrez l’ensemble des soins que nous prodiguons au centre dentaire MAPSO à Casablanca, dans le cadre de la prise en charge de vos problèmes parodontologiques.',
    'services.paro.diseases.title': 'Les maladies parodontales : gingivite et parodontite',
    'services.paro.diseases.desc': 'Les maladies parodontales sont des maladies et conditions pathologiques affectant les tissus de support des dents, c’est-à-dire l’os et la gencive, le cément et le ligament alvéolo-dentaire (ou desmodonte). La gingivite et la parodontite sont des infections causées par l’accumulation de bactéries pathogènes et de leurs toxines sur le rebord de la gencive au pourtour des dents et doivent être prises en charge pour éviter les complications.',
    'services.paro.bilan.title': 'Bilan parodontal',
    'services.paro.bilan.desc': 'Pour préserver votre capital bucco-dentaire, il est indispensable de faire évaluer et de prendre soin de vos gencives. Votre dentiste réalise cette évaluation grâce à un bilan parodontal qui se déroule en plusieurs étapes : interrogatoire médical, analyse clinique, bilan radiologique et tests bactériens dans certains cas.',
    'services.paro.maintenance.title': 'La maintenance parodontale',
    'services.paro.maintenance.desc': 'La maintenance parodontale est la troisième phase de traitement des parodontites après le traitement non-chirurgical et le traitement chirurgical s’il a été nécessaire. ll s’agit d’un suivi du patient et de son parodonte pour anticiper ou intercepter toute récidive de la maladie.',
    'services.paro.surfacage.title': 'Surfaçage radiculaire',
    'services.paro.surfacage.desc': 'Le surfaçage radiculaire est une méthode de traitement de la parodontite. Il vise à nettoyer méticuleusement les surfaces radiculaires pour éliminer la plaque dentaire et le tartre à la surface des racines, mais aussi à l’intérieur de la poche parodontale afin d’éliminer les bactéries qui causent les maladies de gencive.',
    'services.esth.title': 'Soins Esthétiques',
    'services.esth.q1': 'Qu’est-ce que la dentisterie esthétique ?',
    'services.esth.p1': 'La dentisterie esthétique regroupe l’ensemble des techniques dentaires visant à améliorer et restaurer la beauté naturelle de vos dents, à réhausser l’attrait esthétique de votre sourire, tout en maintenant la santé et la fonctionnalité de vos dents. La dentisterie esthétique peut améliorer votre image de soi et avoir un impact physique et psychologique positif.',
    'services.esth.q2': 'Pourquoi aurais-je besoin de dentisterie esthétique ?',
    'services.esth.p2': 'Les indications de la dentisterie esthétique sont nombreuses et correspondent à un grand nombre de situations cliniques. Les motifs de la consultation esthétique les plus fréquentes sont les suivants :',
    'services.esth.list.item1': 'Remplacer une (ou plusieurs) dent(s) manquante(s), particulièrement dans le secteur antérieur.',
    'services.esth.list.item2': '« Réparer » une dent cassée, déformée ou ébréchée.',
    'services.esth.list.item3': 'Dents tâchées, jaunâtres, grisâtres ou colorées.',
    'services.esth.list.item4': 'L’alignement de votre sourire ne vous convient pas.',
    'services.esth.list.item5': 'Sourire trop « gingival » (gencives visibles).',
    'services.esth.facettes.title': 'Les facettes dentaires',
    'services.esth.facettes.desc': 'Une facette dentaire est une petite coque conçue en céramique pour recouvrir votre dent existante et masquer les défauts tels qu’une couleur disgracieuse ou un mauvais alignement.',
    'services.esth.couronnes.title': 'Les couronnes céramo-céramiques',
    'services.esth.couronnes.desc': 'Composées de zircone et de céramique cosmétique, ces couronnes sans armature métallique offrent un résultat esthétique de haut niveau et un rendu naturel.',
    'services.esth.inlays.title': 'Les inlays-onlays',
    'services.esth.inlays.desc': 'Techniques de restauration indirecte pour remplacer une cavité importante ou recouvrir une partie de la dent, alliant esthétique et solidité.',
    'services.esth.blanchiment.title': 'Le blanchiment dentaire',
    'services.esth.blanchiment.desc': 'Technique professionnelle par gouttières permettant de retrouver la couleur naturelle des dents sans altérer l’émail, pour un sourire plus éclatant.',
    'services.omni.title': 'Soins Omnipratiques',
    'services.omni.p1': 'Au Centre Dentaire MAPSO, nous réalisons tous les soins d’omnipratique dentaire pour prévenir l’apparition des caries, infections, pathologies dentaires ou les traiter si elles sont déjà existantes. Ces soins sont nombreux et couvrent toutes les pathologies des différentes structures de votre bouche, les plus courantes étant les caries dentaires, la gestion du tartre ou encore les dévitalisations dentaires.',
    'services.omni.detartrage.title': 'Détartrage et polissage',
    'services.omni.detartrage.desc': 'Au fil du temps, votre bouche produit naturellement du tartre et son accumulation peut entraîner l’apparition d’une gingivite ou une parodontite et venir ternir votre sourire qui perdra de son éclat. Une fois constitué, le tartre ne peut plus être éliminé par le brossage et vous avez besoin de réaliser une séance de détartrage chez votre dentiste. Chez MAPSO Dental Center, nous sommes munis de la dernière technologie AQUACARE qui permet d’effectuer un détartrage et polissage de qualité.',
    'services.omni.composites.title': 'Les composites dentaires',
    'services.omni.composites.desc': 'La résine composite dentaire est un matériau de couleur blanche, très esthétique puisqu’il se décline dans de nombreuses teintes afin de s’adapter au mieux au coloris naturel de votre denture. Il permet de restaurer les dents antérieures et postérieures, notamment lorsque celles-ci ont subi une carie, une fracture ou ont une mauvaise position.',
    'services.omni.endodontie.title': 'Traitements endodontiques ou dévitalisations',
    'services.omni.endodontie.desc': 'Le traitement de canal consiste à retirer la partie interne et vivante de la dent, à désinfecter tout le système de canaux internes, à les élargir et à les remplir d’un matériau d’obturation pour les sceller. Votre dentiste vous conseillera toujours ce type de traitement plutôt que l’extraction quand cela est possible. En effet, même dévitalisée, votre dent assure de nombreuses fonctions : mastication, maintien de la position des dents et préservation de l’os alvéolaire.',
    'services.proth.title': 'Soins Prothétiques',
    'services.proth.p1': 'La prothèse dentaire est un dispositif dentaire remplaçant une ou plusieurs dents absentes dans le but de reformer une arcade dentaire complète.',
    'services.proth.p2': 'Votre chirurgien-dentiste du centre dentaire MAPSO à Casablanca dispose de nombreuses solutions prothétiques pour compenser des édentements, reconstruire des dents délabrées ou encore améliorer l’esthétique de votre sourire. Le choix dépendra de votre situation clinique et de vos attentes.',
    'services.proth.couronne.title': 'La couronne prothétique',
    'services.proth.couronne.desc': 'Les couronnes dentaires sont des prothèses fixes permettant de reconstruire des dents abîmées, cassées ou dévitalisées. Une couronne va venir chapeauter votre dent et la recouvrir entièrement pour la solidifier tout en restaurant son esthétique et son potentiel masticatoire.',
    'services.proth.bridge.title': 'Le bridge dentaire',
    'services.proth.bridge.desc': 'Un bridge (pont) est une prothèse dentaire qui forme un pont entre plusieurs dents pour remplacer une ou deux dents manquantes, en prenant appui sur les dents adjacentes (dents piliers). C’est une solution fixe, rapide et esthétique.',
    'services.proth.amovible_partielle.title': 'Prothèses amovibles partielles',
    'services.proth.amovible_partielle.desc': 'Remplacent généralement plusieurs dents manquantes. Elle est partielle car elle ne remplace pas toutes les dents et amovible car elle n’est pas collée. Elle s’appuie sur les gencives et les dents adjacentes à l’aide de crochets pour restaurer la mastication et le sourire.',
    'services.proth.amovible_complete.title': 'La prothèse amovible complète',
    'services.proth.amovible_complete.desc': 'Indiquée lorsqu’il y a une absence totale de dents. Souvent appelée « dentier », elle remplace la totalité des dents du haut ou du bas et peut s’enlever facilement. Elle tient en place par effet de ventouse (succion) grâce à la salive.',
    
    // Footer
    'footer.about': 'Infrastructure contemporaine et techniques de pointe pour des soins dentaires d\'excellence à Casablanca.',
    'footer.nav': 'Navigation',
    'footer.contact': 'Contact',
    'footer.rights': 'Tous droits réservés.',

    // Appointment
    'appointment.tag': 'Prise de rendez-vous',
    'appointment.title': 'Prendre rendez-vous',
    'appointment.form.title': 'Formulaire de rendez-vous',
    'appointment.form.desc': 'Veuillez remplir le formulaire ci-dessous pour demander un rendez-vous.',
    'appointment.form.date': 'Date souhaitée',
    'appointment.form.time': 'Heure souhaitée',
    'appointment.form.service': 'Service souhaité',
    'appointment.form.submit': 'Confirmer le rendez-vous',
  },
  AR: {
    // Header
    'nav.home': 'الرئيسية',
    'nav.soins': 'علاجاتنا',
    'nav.urgences': 'المستعجلات',
    'nav.conseils': 'نصائح',
    'nav.contact': 'اتصل بنا',
    'nav.appointment': 'حجز موعد',
    'header.location': 'الدار البيضاء، المغرب',
    'header.subtitle': 'مركز طب الأسنان',
    'header.language': 'اللغة',
    
    // Home
    'hero.welcome': 'مرحباً بكم في مابسو',
    'hero.title': 'ابتسامتكم، شغفنا',
    'hero.subtitle': 'رعاية أسنان متميزة في قلب الدار البيضاء',
    'hero.cta': 'حجز موعد',
    'hero.call': 'اتصل بنا',
    
    'services.title': 'خدماتنا',
    'services.subtitle': 'مجموعة كاملة من العلاجات لجميع أفراد الأسرة',
    'services.details': 'عرض التفاصيل',
    'services.more': 'اعرف المزيد',

    'service.omni.title': 'العلاجات العامة',
    'service.omni.desc': 'نقوم بجميع علاجات طب الأسنان العام للوقاية من ظهور التسوس والعدوى وأمراض الأسنان...',
    'service.ortho.title': 'تقويم الأسنان',
    'service.ortho.desc': 'استفد من علاجات تقويم الأسنان التي تساعدك على استعادة وظائف وجماليات فكك.',
    'service.esth.title': 'العلاجات التجميلية',
    'service.esth.desc': 'لتجميل ابتسامتك وتحسين واستعادة الجمال الطبيعي لأسنانك...',
    'service.paro.title': 'أمراض اللثة',
    'service.paro.desc': 'أمراض اللثة ناتجة عن عدوى بكتيرية. اكتشف جميع العلاجات...',
    'service.proth.title': 'علاجات التعويضات السنية',
    'service.proth.desc': 'يمكنك استبدال سن مفقود أو أكثر بجهاز أسنان...',
    'service.impl.title': 'زراعة الأسنان',
    'service.impl.desc': 'تجنب ذوبان عظم الفك الناتج عن فقدان سن أو أكثر...',

    'features.team.title': 'فريق ذو خبرة',
    'features.team.desc': 'فريق محترف ومتجانس في خدمتكم.',
    'features.human.title': 'نهج إنساني',
    'features.human.desc': 'نهج إنساني في جراحة الأسنان.',
    'features.client.title': 'خدمة العملاء',
    'features.client.desc': 'نستقبلكم بفرح، ونستجيب لجميع طلباتكم.',
    'features.covid.title': 'كوفيد 19',
    'features.covid.desc': 'التدابير المتخذة لحمايتكم ومنع انتشار الفيروس.',
    'features.advice.title': 'نصائح',
    'features.advice.desc': 'نقدم لكم الاستماع والمشورة الشخصية عبر الهاتف.',
    'features.urgency.title': 'حالات طوارئ الأسنان',
    'features.urgency.desc': 'دعم مخصص للتكفل الأمثل بحالات طوارئ الأسنان الخاصة بكم.',

    'about.tag': 'من نحن',
    'about.title': 'طبيب أسنانك الموثوق في الدار البيضاء',
    'about.p1': 'يمارس أطباء الأسنان لدينا في الدار البيضاء المعاريف العديد من الخدمات التي يقدمها المركز، مثل: العناية بالأسنان، وتقويم الأسنان، وزراعة الأسنان، وطب أسنان الأطفال، ولكن أيضًا تحسين وإعادة بناء جماليات الأسنان والابتسامة.',
    'about.p2': 'بفضل الأدوات المتطورة، يستطيع فريق الممارسين لدينا إجراء فحوصات كاملة ودقيقة لضمان أفضل النتائج.',
    'about.cta': 'تعرف علينا أكثر',

    'quick.urgency.title': 'حالات الطوارئ',
    'quick.urgency.desc': 'رعاية فورية',
    'quick.advice.title': 'نصائح',
    'quick.advice.desc': 'استماع ومرافقة',
    'quick.find.title': 'تجدنا',
    'quick.find.desc': 'في قلب الدار البيضاء',

    'cta.title': 'هل تحتاج إلى معلومات؟',
    'cta.subtitle': 'فريقنا تحت تصرفك للإجابة على جميع أسئلتك.',

    // Urgences
    'urgences.tag': 'رعاية سريعة',
    'urgences.title': 'حالات الطوارئ',
    'urgences.intro': 'حادث، عدوى، أو صدمة... غالباً ما تسبب حالات الطوارئ السنية آلاماً حادة وتتطلب تدخلاً سريعاً.',
    'urgences.availability': 'توفر فوري',
    'urgences.hours.title': 'خلال ساعات عمل مركز مابسو',
    'urgences.hours.desc': 'أطباؤنا ذوو الخبرة يستقبلونكم من الاثنين إلى الجمعة من الساعة 9:00 صباحاً حتى 7:00 مساءً لأي حالة طارئة.',
    'urgences.hours.note': 'اتصل بسكرتاريتنا للحصول على رعاية ذات أولوية.',
    'urgences.more': 'اعرف المزيد',
    
    'urgences.pain.title': 'آلام الأسنان',
    'urgences.pain.desc': 'يمكن أن تكون آلام الأسنان لا تطاق وتتطلب رعاية فورية، خاصة في حالة العدوى.',
    'urgences.proth.title': 'طوارئ التعويضات السنية',
    'urgences.proth.desc': 'تاج مخلوع، جهاز مكسور أو مؤلم... الرعاية السريعة ضرورية لراحتك.',
    'urgences.paro.title': 'طوارئ أمراض اللثة',
    'urgences.paro.desc': 'التهابات اللثة أو العظام أو الأربطة. تتطلب هذه الحالات تدخلاً متخصصاً.',
    'urgences.trauma.title': 'طوارئ الصدمات',
    'urgences.trauma.desc': 'الصدمات المرتبطة بالرياضة أو الحوادث، وهي شائعة بشكل خاص عند الأطفال.',

    // Conseils
    'conseils.tag': 'النظافة والوقاية',
    'conseils.title': 'نصائحنا',
    'conseils.intro1': 'أنت الفاعل الرئيسي في صحة فمك وأسنانك. النظافة أساسية للحفاظ على ابتسامتك طوال حياتك.',
    'conseils.intro2': 'خبراء مابسو يرافقونكم في اختيار أدواتكم وتقنيات التنظيف الخاصة بكم.',
    'conseils.expert': 'نصيحة خبير',
    'conseils.cta.title': 'هل تحتاج إلى فحص كامل؟',
    'conseils.cta.desc': 'احجز موعداً لاستشارة فحص واحصل على نصائح شخصية.',
    'conseils.cta.btn': 'حجز موعد',

    'conseils.manual.title': 'فرشاة الأسنان اليدوية',
    'conseils.manual.desc': 'يعد تنظيف الأسنان بانتظام واستخدام خيط الأسنان أمراً ضرورياً لصحة الفم الجيدة للوقاية من تسوس الأسنان.',
    'conseils.mouthwash.title': 'استخدام غسول الفم',
    'conseils.mouthwash.desc': 'لضمان نظافة الفم الجيدة، التوصية الأساسية هي تنظيف أسنانك مرتين إلى ثلاث مرات في اليوم.',
    'conseils.electric.title': 'فرشاة الأسنان الكهربائية',
    'conseils.electric.desc': 'مع فرشاة الأسنان القابلة لإعادة الشحن، تختلف عملية التنظيف تماماً لأن الفرشاة نفسها توفر الحركة اللازمة.',
    'conseils.floss.title': 'استخدام خيط الأسنان',
    'conseils.floss.desc': 'إذا كان التنظيف جزءاً لا يتجزأ من الروتين، فإن استخدام خيط الأسنان هو لفتة أساسية غالباً ما يتم إهمالها.',

    // Contact
    'contact.tag': 'اتصل بنا',
    'contact.title': 'لنتحدث عن ابتسامتك',
    'contact.find.title': 'تجدنا',
    'contact.find.content': 'زاوية شارع القاضي إياس وشارع سعد بن زراعة، عمارة الوصية، الطابق 2، رقم 3 فوق ماكدونالدز، الدار البيضاء 20330',
    'contact.call.title': 'اتصل بنا',
    'contact.call.fix': 'ثابت',
    'contact.email.title': 'البريد الإلكتروني',
    'contact.email.desc': 'أرسل لنا رسالة',
    'contact.hours.title': 'ساعات العمل',
    'contact.hours.mon_thu': 'الاثنين - الخميس',
    'contact.hours.fri': 'الجمعة',
    'contact.hours.sat': 'السبت',
    'contact.form.title': 'أرسل لنا رسالة',
    'contact.form.desc': 'سنرد عليك في أقرب وقت ممكن.',
    'contact.form.name': 'اسمك*',
    'contact.form.name_placeholder': 'الاسم الكامل',
    'contact.form.email': 'بريدك الإلكتروني*',
    'contact.form.subject': 'الموضوع',
    'contact.form.subject_placeholder': 'طلب استفسار',
    'contact.form.message': 'رسالتك*',
    'contact.form.message_placeholder': 'كيف يمكننا مساعدتك؟',
    'contact.form.send': 'إرسال الرسالة',
    'contact.map.cabinet': 'عيادتنا',
    'contact.map.location': 'الدار البيضاء، المعاريف',

    // Appointment
    'appointment.tag': 'حجز موعد',
    'appointment.title': 'حجز موعد',
    'appointment.form.title': 'نموذج حجز الموعد',
    'appointment.form.desc': 'يرجى ملء النموذج أدناه لطلب موعد.',
    'appointment.form.date': 'التاريخ المطلوب',
    'appointment.form.time': 'الوقت المطلوب',
    'appointment.form.service': 'الخدمة المطلوبة',
    'appointment.form.submit': 'تأكيد الموعد',

    // Services
    'services.implant.title': 'زراعة الأسنان',
    'services.implant.p1': 'تعد زراعة الأسنان فرعاً من جراحة الأسنان يمارسه جراح الأسنان وتتكون من وضع غرسات في الفك العلوي و/أو السفلي.',
    'services.implant.p2': 'سيسمح وضع الغرسات هذا باستبدال سن مفقود أو أكثر وبالتالي معالجة المشاكل الجمالية ومشاكل استقرار الفك والمضغ والراحة اليومية.',
    'services.implant.p3': 'تسمح الممارسة الجراحية لزراعة الأسنان أيضًا بتجنب ذوبان عظم الفك الناتج عن فقدان سن أو أكثر مهما كان السبب.',
    'services.implant.pose.title': 'وضع غرسة الأسنان',
    'services.implant.pose.desc': 'غرسة الأسنان هي جذر اصطناعي، نوع من البراغي المصنوعة من التيتانيوم أو الزركونيا، يتم وضعها في العظم السنخي لاستبدال سن مفقود أو أكثر.',
    'services.implant.analysis.title': 'التحليل قبل الزرع',
    'services.implant.analysis.desc': 'قبل أي وضع للغرسات، يلزم إجراء تحليل قبل الزرع لضمان تدخل آمن وموقع مثالي.',
    'services.implant.greffe.title': 'زراعة العظام لغرض الزرع',
    'services.implant.greffe.desc': 'إذا كان حجم العظام غير كافٍ، فستكون هناك حاجة لزراعة العظام لضمان استمرارية الغرسة.',
    'services.implant.sinus.title': 'رفع الجيوب الأنفية',
    'services.implant.sinus.desc': 'تدخل لملء قاع الجيب الفكي باستخدام طعم عظمي للسماح بوضع الغرسات.',
    'services.ortho.title': 'تقويم الأسنان',
    'services.ortho.p1': 'الابتسامة الجمالية والمتناغمة هي اليوم عنصر مهم في الحياة الاجتماعية. إذا كنت تشعر بالحرج من ابتسامتك، فإن تقويم الأسنان هو حل بسيط وفعال لتحسين ابتسامتك ورفاهيتك بشكل كبير.',
    'services.ortho.p2': 'بالنسبة للطفل، الرهان الرئيسي هو النمو المتناغم للفكين والتموضع الصحيح للأسنان لحمايته من أي ضرر جمالي أو في الإطباق عند البلوغ.',
    'services.ortho.how_title': 'كيف يعمل علاج تقويم الأسنان؟',
    'services.ortho.how_desc1': 'تصنع أجهزة تقويم الأسنان من المعدن أو السيراميك أو البلاستيك. يمكن أن تكون قابلة للإزالة أو ثابتة على الأسنان بواسطة "حلقات".',
    'services.ortho.how_desc2': 'لقد ولى زمن الأجهزة المعدنية حصرياً؛ يمكنك الآن اختيار دعامات شفافة أو معدنية. اليوم، كل عمر هو عمر مثالي لارتداء جهاز تقويم الأسنان!',
    'services.ortho.duration_title': 'ما هي مدة علاج تقويم الأسنان؟',
    'services.ortho.duration_desc1': 'تختلف مدة العلاج ويمكن أن تستمر بين سنة وثلاث سنوات، اعتماداً على عدة عوامل، بما في ذلك العمر وطريقة العلاج.',
    'services.ortho.duration_desc2': 'قبل البدء في رعاية تقويم الأسنان، سيناقش أخصائي تقويم الأسنان جميع الخيارات العلاجية المتاحة ويعطيك تقديراً للمدة الإجمالية لعلاجك.',
    'services.ortho.invisible.title': 'تقويم الأسنان غير المرئي',
    'services.ortho.invisible.desc': 'هناك العديد من علاجات تقويم الأسنان غير المرئية التي تسمح بمعالجة سوء تموضع أسنانك بأكبر قدر من السرية.',
    'services.ortho.adult.title': 'تقويم الأسنان للكبار',
    'services.ortho.adult.desc': 'في حالة تقويم الأسنان للكبار، سيرتبط اختيار علاجك برغباتك واحتياجاتك، سواء كان جهازاً كلاسيكياً أو حلولاً أكثر سرية.',
    'services.ortho.invisalign.title': 'إنفيسالاين',
    'services.ortho.invisalign.desc': 'تقنية تستخدم قوالب شفافة وغير مرئية مصنوعة حسب المقاس لمحاذاة الأسنان بأكثر الطرق سرية ممكنة.',
    'services.ortho.kids.title': 'تقويم الأسنان للأطفال والمراهقين',
    'services.ortho.kids.desc': 'مخصص للوقاية وتصحيح تشوهات الأسنان لضمان شيخوخة جيدة للأسنان واللثة.',
    'services.paro.title': 'أمراض اللثة',
    'services.paro.p1': 'أمراض اللثة هي جزء من طب الأسنان المتخصص في علاج الأنسجة الداعمة للسن: اللثة، الأنسجة العظمية، الملاط والرباط اللثوي. تعود أمراض اللثة إلى عدوى بكتيرية.',
    'services.paro.p2': 'اكتشف جميع العلاجات التي نقدمها في مركز مابسو للأسنان في الدار البيضاء، في إطار التكفل بمشاكل اللثة الخاصة بك.',
    'services.paro.diseases.title': 'أمراض اللثة: التهاب اللثة والتهاب دواعم السن',
    'services.paro.diseases.desc': 'أمراض اللثة هي أمراض وحالات مرضية تصيب الأنسجة الداعمة للأسنان، أي العظام واللثة. التهاب اللثة والتهاب دواعم السن هي عدوى ناتجة عن تراكم البكتيريا الضارة وسمومها على حافة اللثة حول الأسنان ويجب التكفل بها لتجنب المضاعفات.',
    'services.paro.bilan.title': 'فحص اللثة',
    'services.paro.bilan.desc': 'للحفاظ على صحة الفم والأسنان، من الضروري تقييم اللثة والاعتناء بها. يقوم طبيب الأسنان بهذا التقييم من خلال فحص اللثة الذي يتم على عدة مراحل: استجواب طبي، تحليل سريري، فحص إشعاعي واختبارات بكتيرية في بعض الحالات.',
    'services.paro.maintenance.title': 'صيانة اللثة',
    'services.paro.maintenance.desc': 'صيانة اللثة هي المرحلة الثالثة من علاج التهاب دواعم السن بعد العلاج غير الجراحي والعلاج الجراحي إذا لزم الأمر. وهي عبارة عن متابعة للمريض ولثته لاستباق أو اعتراض أي انتكاسة للمرض.',
    'services.paro.surfacage.title': 'تسوية الجذور',
    'services.paro.surfacage.desc': 'تسوية الجذور هي طريقة لعلاج التهاب دواعم السن. تهدف إلى تنظيف أسطح الجذور بدقة لإزالة اللويحة السنية والجير من على سطح الجذور، وكذلك داخل الجيب اللثوي من أجل القضاء على البكتيريا التي تسبب أمراض اللثة.',
    'services.esth.title': 'العلاجات التجميلية',
    'services.esth.q1': 'ما هو طب الأسنان التجميلي؟',
    'services.esth.p1': 'يجمع طب الأسنان التجميلي جميع تقنيات الأسنان التي تهدف إلى تحسين واستعادة الجمال الطبيعي لأسنانك، وتعزيز الجاذبية الجمالية لابتسامتك، مع الحفاظ على صحة ووظيفة أسنانك. يمكن لطب الأسنان التجميلي أن يحسن صورتك الذاتية ويكون له تأثير جسدي ونفسي إيجابي.',
    'services.esth.q2': 'لماذا قد أحتاج إلى طب الأسنان التجميلي؟',
    'services.esth.p2': 'دواعي طب الأسنان التجميلي عديدة وتتوافق مع عدد كبير من الحالات السريرية. الأسباب الأكثر شيوعاً للاستشارة التجميلية هي:',
    'services.esth.list.item1': 'استبدال سن (أو أكثر) مفقود، خاصة في المنطقة الأمامية.',
    'services.esth.list.item2': '«إصلاح» سن مكسور أو مشوه أو مشروخ.',
    'services.esth.list.item3': 'أسنان ملطخة أو مائلة للصفرة أو الرمادية.',
    'services.esth.list.item4': 'اصطفاف ابتسامتك لا يناسبك.',
    'services.esth.list.item5': 'ابتسامة "لثوية" للغاية (اللثة تظهر بوضوح).',
    'services.esth.facettes.title': 'قشور الأسنان (الفينير)',
    'services.esth.facettes.desc': 'قشرة الأسنان هي نوع من الغطاء الصغير المصنوع من السيراميك لتغطية سنك الموجود وإخفاء العيوب مثل اللون غير المرغوب فيه أو الاصطفاف السيئ.',
    'services.esth.couronnes.title': 'التيجان الخزفية الكاملة',
    'services.esth.couronnes.desc': 'تتكون من الزركونيا والسيراميك التجميلي، وتتميز هذه التيجان بعدم وجود إطار معدني، مما يوفر نتيجة جمالية عالية المستوى ومظهراً طبيعياً.',
    'services.esth.inlays.title': 'الحشوات المصبوبة (Inlays-Onlays)',
    'services.esth.inlays.desc': 'تقنيات ترميم غير مباشرة لاستبدال تجويف كبير أو تغطية جزء من السن، تجمع بين الجمال والمتانة.',
    'services.esth.blanchiment.title': 'تبييض الأسنان',
    'services.esth.blanchiment.desc': 'تقنية احترافية باستخدام القوالب تسمح باستعادة اللون الطبيعي للأسنان دون الإضرار بالمينا، لابتسامة أكثر إشراقاً.',
    'services.omni.title': 'العلاجات العامة',
    'services.omni.p1': 'في مركز مابسو للأسنان، نقوم بجميع علاجات طب الأسنان العام للوقاية من ظهور التسوس والعدوى وأمراض الأسنان أو علاجها إذا كانت موجودة بالفعل. هذه العلاجات عديدة وتغطي جميع أمراض الهياكل المختلفة لفمك، وأكثرها شيوعاً هي تسوس الأسنان، وإدارة الجير أو حتى سحب العصب.',
    'services.omni.detartrage.title': 'إزالة الجير والتلميع',
    'services.omni.detartrage.desc': 'بمرور الوقت، ينتج فمك الجير بشكل طبيعي ويمكن أن يؤدي تراكمه إلى ظهور التهاب اللثة أو التهاب دواعم السن ويجعل ابتسامتك تفقد بريقها. بمجرد تكوينه، لا يمكن إزالة الجير عن طريق التنظيف بالفرشاة وتحتاج إلى إجراء جلسة تنظيف عند طبيب الأسنان. في مركز مابسو للأسنان، نحن مجهزون بأحدث تقنيات AQUACARE التي تسمح بإجراء تنظيف وتلميع عالي الجودة.',
    'services.omni.composites.title': 'حشوات الكومبوزيت',
    'services.omni.composites.desc': 'راتنج الكومبوزيت للأسنان هو مادة بيضاء اللون، جمالية للغاية لأنها تأتي في العديد من الظلال لتناسب اللون الطبيعي لأسنانك بشكل أفضل. يسمح بترميم الأسنان الأمامية والخلفية، خاصة عندما تتعرض للتسوس أو الكسر أو تكون في وضع سيئ.',
    'services.omni.endodontie.title': 'علاجات قناة الجذر أو سحب العصب',
    'services.omni.endodontie.desc': 'يتكون علاج قناة الجذر من إزالة الجزء الداخلي والحي من السن، وتطهير نظام القنوات الداخلية بالكامل، وتوسيع القنوات الرئيسية وملئها بمادة حشو لإغلاقها. سينصحك طبيب أسنانك دائماً بهذا النوع من العلاج بدلاً من الخلع عندما يكون ذلك ممكناً. في الواقع، حتى بعد سحب العصب، تؤدي سنك العديد من الوظائف: المضغ بكفاءة مرضية، والحفاظ على وضع أسنانك بالنسبة لبعضها البعض، وأخيراً الحفاظ على عظم الفك حولها.',
    'services.proth.title': 'علاجات التعويضات السنية',
    'services.proth.p1': 'بدلة الأسنان هي جهاز أسنان يحل محل سن واحد أو أكثر من الأسنان المفقودة بهدف إعادة تشكيل قوس أسنان كامل.',
    'services.proth.p2': 'يتوفر جراح الأسنان في مركز مابسو بالدار البيضاء على العديد من الحلول التعويضية لتعويض الأسنان المفقودة أو إعادة بناء الأسنان المتضررة أو تحسين جمالية ابتسامتك. سيعتمد الاختيار على حالتك السريرية وتوقعاتك.',
    'services.proth.couronne.title': 'التاج التعويضي',
    'services.proth.couronne.desc': 'تيجان الأسنان هي أطراف صناعية ثابتة تسمح بإعادة بناء الأسنان المتضررة أو المكسورة أو المسحوب عصبها. سيقوم التاج بتغطية سنك بالكامل لتقويته مع استعادة جماليته وقدرته على المضغ.',
    'services.proth.bridge.title': 'جسر الأسنان',
    'services.proth.bridge.desc': 'الجسر هو طرف صناعي للأسنان يشكل جسراً بين عدة أسنان لتعويض سن واحد أو اثنين مفقودين، بالاعتماد على الأسنان المجاورة (الأسنان الداعمة). إنه حل ثابت وسريع وجمالي.',
    'services.proth.amovible_partielle.title': 'أطقم الأسنان المتحركة الجزئية',
    'services.proth.amovible_partielle.desc': 'تحل محل عدة أسنان مفقودة بشكل عام. وهي جزئية لأنها لا تعوض جميع الأسنان، ومتحركة لأنه لا يتم لصقها. تعتمد على اللثة والأسنان المجاورة باستخدام خطافات لاستعادة المضغ والابتسامة.',
    'services.proth.amovible_complete.title': 'طقم الأسنان المتحرك الكامل',
    'services.proth.amovible_complete.desc': 'يستعمل عند غياب الأسنان بشكل كامل. غالباً ما يسمى "طقم الأسنان"، وهو يحل محل جميع أسنان الفك العلوي أو السفلي ويمكن إزالته بسهولة. يثبت في مكانه عن طريق تأثير الشفط بفضل اللعاب.',

    // Footer
    'footer.about': 'بنية تحتية معاصرة وتقنيات متطورة لرعاية أسنان متميزة في الدار البيضاء.',
    'footer.nav': 'التنقل',
    'footer.contact': 'اتصل بنا',
    'footer.rights': 'جميع الحقوق محفوظة.',
  },
  EN: {
    // Header
    'nav.home': 'Home',
    'nav.soins': 'Our Care',
    'nav.urgences': 'Emergencies',
    'nav.conseils': 'Advice',
    'nav.contact': 'Contact',
    'nav.appointment': 'Book Appointment',
    'header.location': 'Casablanca, Morocco',
    'header.subtitle': 'Dental Center',
    'header.language': 'Language',
    
    // Home
    'hero.welcome': 'Welcome to MAPSO',
    'hero.title': 'Your Smile, Our Passion',
    'hero.subtitle': 'Excellent dental care in the heart of Casablanca',
    'hero.cta': 'Book an Appointment',
    'hero.call': 'Call the Office',
    
    'services.title': 'Our Services',
    'services.subtitle': 'A complete range of care for the whole family',
    'services.details': 'View Details',
    'services.more': 'Read More',

    'service.omni.title': 'General Care',
    'service.omni.desc': 'We perform all general dental care to prevent the appearance of cavities, infections...',
    'service.ortho.title': 'Orthodontics',
    'service.ortho.desc': 'Enjoy orthodontic care that helps you restore the functionality and aesthetics of your jaw.',
    'service.esth.title': 'Aesthetic Care',
    'service.esth.desc': 'To beautify your smile, improve and restore the natural beauty of your teeth...',
    'service.paro.title': 'Periodontology',
    'service.paro.desc': 'Periodontal diseases are due to bacterial infections. Discover all the treatments...',
    'service.proth.title': 'Prosthetic Care',
    'service.proth.desc': 'You can replace one or more missing teeth with a dental device...',
    'service.impl.title': 'Implantology',
    'service.impl.desc': 'Avoid jaw bone loss following the loss of one or more teeth...',

    'features.team.title': 'Experienced Team',
    'features.team.desc': 'A professional and homogeneous team at your service.',
    'features.human.title': 'Human Approach',
    'features.human.desc': 'A human approach to dental surgery.',
    'features.client.title': 'Customer Service',
    'features.client.desc': 'We welcome you with joy, we respond to all your requests.',
    'features.covid.title': 'COVID 19',
    'features.covid.desc': 'Measures in place to protect you and prevent the spread of the virus.',
    'features.advice.title': 'Advice',
    'features.advice.desc': 'We offer you listening and personalized advice by phone.',
    'features.urgency.title': 'Dental Emergencies',
    'features.urgency.desc': 'Tailor-made support for optimal management of your dental emergencies.',

    'about.tag': 'About Us',
    'about.title': 'Your Trusted Dentist in Casablanca',
    'about.p1': 'Our dentists in Casablanca Maarif practice many services that the center offers, such as: dental care, orthodontics, implantology, pedodontics but also the improvement and reconstruction of dental aesthetics and the smile.',
    'about.p2': 'Thanks to state-of-the-art tools, our team of practitioners is able to carry out complete and thorough examinations to guarantee you the best result.',
    'about.cta': 'Get to know us better',

    'quick.urgency.title': 'Emergencies',
    'quick.urgency.desc': 'Immediate care',
    'quick.advice.title': 'Advice',
    'quick.advice.desc': 'Listening and support',
    'quick.find.title': 'Find Us',
    'quick.find.desc': 'In the heart of Casablanca',

    'cta.title': 'Need information?',
    'cta.subtitle': 'Our team is at your disposal to answer all your questions.',

    // Urgences
    'urgences.tag': 'Rapid management',
    'urgences.title': 'Dental Emergencies',
    'urgences.intro': 'Accident, infection, or trauma... Dental emergencies often cause sharp pain and require rapid intervention.',
    'urgences.availability': 'Immediate availability',
    'urgences.hours.title': 'DURING MAPSO CENTER OPENING HOURS',
    'urgences.hours.desc': 'Our experienced dentists welcome you from Monday to Friday from 9:00 am to 7:00 pm for any emergency.',
    'urgences.hours.note': 'Contact our secretariat for priority management.',
    'urgences.more': 'Read more',
    
    'urgences.pain.title': 'Dental Pain',
    'urgences.pain.desc': 'Dental pain can be unbearable and require immediate care, especially in case of infection.',
    'urgences.proth.title': 'Prosthetic Emergencies',
    'urgences.proth.desc': 'Unsealed crown, broken or hurting device... Rapid management is essential for your comfort.',
    'urgences.paro.title': 'Periodontal Emergencies',
    'urgences.paro.desc': 'Infections of the gums, bone or ligaments. These pathologies require specialized intervention.',
    'urgences.trauma.title': 'Traumatic Emergencies',
    'urgences.trauma.desc': 'Trauma related to sport or accidents, particularly frequent in children.',

    // Conseils
    'conseils.tag': 'Hygiene & Prevention',
    'conseils.title': 'Our Advice',
    'conseils.intro1': 'You are the main actor in your oral health. Hygiene is fundamental to preserve your smile throughout your life.',
    'conseils.intro2': 'MAPSO experts accompany you in the choice of your tools and brushing techniques.',
    'conseils.expert': 'Expert advice',
    'conseils.cta.title': 'Need a complete check-up?',
    'conseils.cta.desc': 'Make an appointment for a check-up consultation and receive personalized advice.',
    'conseils.cta.btn': 'Make an appointment',

    'conseils.manual.title': 'Manual toothbrush',
    'conseils.manual.desc': 'Regular brushing and flossing are essential for good oral health to prevent cavities.',
    'conseils.mouthwash.title': 'Using mouthwash',
    'conseils.mouthwash.desc': 'To ensure good oral hygiene, the essential recommendation is to brush your teeth two to three times a day.',
    'conseils.electric.title': 'Electric toothbrush',
    'conseils.electric.desc': 'With a rechargeable toothbrush, the brushing action is very different because the brush itself provides the necessary movement.',
    'conseils.floss.title': 'Using dental floss',
    'conseils.floss.desc': 'If brushing is an integral part of the routine, using dental floss is an essential gesture often neglected.',

    // Contact
    'contact.tag': 'Contact Us',
    'contact.title': "Parlons de votre sourire",
    'contact.find.title': 'Find us',
    'contact.find.content': "Angle Rue Cadi Iass et Rue Saad Bnou Zarara, Imm EL WASSIA, étg 2, n3 Au dessus de McDonald's, Casablanca 20330",
    'contact.call.title': 'Call us',
    'contact.call.fix': 'Fix',
    'contact.email.title': 'Email Address',
    'contact.email.desc': 'Send us a message',
    'contact.hours.title': 'Working Hours',
    'contact.hours.mon_thu': 'Mon - Thu',
    'contact.hours.fri': 'Fri',
    'contact.hours.sat': 'Sat',
    'contact.form.title': 'Send us a message',
    'contact.form.desc': 'We will reply to you as soon as possible.',
    'contact.form.name': 'Your name*',
    'contact.form.name_placeholder': 'John Doe',
    'contact.form.email': 'Your email*',
    'contact.form.subject': 'Subject',
    'contact.form.subject_placeholder': 'Inquiry request',
    'contact.form.message': 'Your message*',
    'contact.form.message_placeholder': 'How can we help you?',
    'contact.form.send': 'Send Message',
    'contact.map.cabinet': 'Our Cabinet',
    'contact.map.location': 'Casablanca, Maarif',

    // Services
    'services.implant.title': 'Implantology',
    'services.implant.p1': 'Dental implantology is a branch of dental surgery that consists of placing implants in the upper and/or lower jaw.',
    'services.implant.p2': 'This allows replacing missing teeth and addressing aesthetic, stability, and chewing problems.',
    'services.implant.p3': 'Surgical practice of implantology also prevents jaw bone loss following the loss of one or more teeth.',
    'services.implant.pose.title': 'Dental Implant Placement',
    'services.implant.pose.desc': 'A dental implant is an artificial root, a titanium or zirconia screw, placed in the bone to replace missing teeth.',
    'services.implant.analysis.title': 'Pre-implant Analysis',
    'services.implant.analysis.desc': 'Before any implant placement, a pre-implant analysis is required to ensure safety and optimal positioning.',
    'services.implant.greffe.title': 'Bone Graft for Implants',
    'services.implant.greffe.desc': 'If bone volume is insufficient, a bone graft will be necessary to ensure the long-term durability of the implant.',
    'services.implant.sinus.title': 'Sinus Lift',
    'services.implant.sinus.desc': 'Procedure to fill the bottom of the maxillary sinus with a bone graft to allow implant placement.',
    'services.ortho.title': 'Orthodontics',
    'services.ortho.p1': 'An aesthetic and harmonious smile is an important element of social life today. If you are self-conscious about your smile, find your teeth misaligned or your smile a bit too gummy, orthodontics is a simple and effective solution to greatly improve your smile and well-being.',
    'services.ortho.p2': 'For a child, the main challenge is a harmonious growth of the jaws and a correct positioning of their teeth to protect them from any aesthetic or occlusion prejudice in adulthood.',
    'services.ortho.how_title': 'How does orthodontic treatment work?',
    'services.ortho.how_desc1': 'Orthodontic appliances are made of metal, ceramic or plastic. They can be removable or fixed to the teeth by "brackets". By exercising a gentle and constant force, they slowly move the teeth into the correct position.',
    'services.ortho.how_desc2': 'The time of exclusively metal appliances is over; you can now choose transparent or metal supports. Today, any age is an ideal age to wear braces!',
    'services.ortho.duration_title': 'What is the duration of orthodontic treatment?',
    'services.ortho.duration_desc1': 'The duration of treatment varies and can last between one and three years, depending on several factors, including age, treatment method and importance of treatment.',
    'services.ortho.duration_desc2': 'Before starting your orthodontic care, your orthodontist will discuss all available therapeutic options and give you an estimate of the total duration of your treatment.',
    'services.ortho.invisible.title': 'Invisible Orthodontics',
    'services.ortho.invisible.desc': 'There are many invisible orthodontic treatments that allow treating misalignments of your teeth with the utmost discretion.',
    'services.ortho.adult.title': 'Adult Orthodontics',
    'services.ortho.adult.desc': 'In the case of adult orthodontics, the choice of your treatment will be linked to your wishes and needs, whether it is a classic appliance or more discrete solutions.',
    'services.ortho.invisalign.title': 'Invisalign',
    'services.ortho.invisalign.desc': 'Technique using custom-made transparent and invisible aligners to align teeth in the most discrete way possible.',
    'services.ortho.kids.title': 'Children and Adolescent Orthodontics',
    'services.ortho.kids.desc': 'Dedicated to the prevention and correction of dentition anomalies to ensure good aging of teeth and gums.',
    'services.paro.title': 'Periodontics',
    'services.paro.p1': 'Periodontics is the part of dentistry that specializes in the treatment of the periodontium, i.e., the supporting tissues of the tooth: gum, bone tissue, cementum, and periodontal ligament. Periodontal diseases are due to bacterial infections.',
    'services.paro.p2': 'Discover all the care we provide at the MAPSO dental center in Casablanca, as part of the management of your periodontal problems.',
    'services.paro.diseases.title': 'Periodontal diseases: gingivitis and periodontitis',
    'services.paro.diseases.desc': 'Periodontal diseases are diseases and pathological conditions affecting the supporting tissues of the teeth, i.e., the bone and the gum. Gingivitis and periodontitis are infections caused by the accumulation of pathogenic bacteria and their toxins on the gum line around the teeth and must be managed to avoid complications.',
    'services.paro.bilan.title': 'Periodontal assessment',
    'services.paro.bilan.desc': 'To preserve your oral health capital, it is essential to have your gums evaluated and taken care of. Your dentist performs this evaluation through a periodontal assessment that takes place in several stages: medical interview, clinical analysis, radiological assessment, and bacterial tests in some cases.',
    'services.paro.maintenance.title': 'Periodontal maintenance',
    'services.paro.maintenance.desc': 'Periodontal maintenance is the third phase of periodontitis treatment after non-surgical treatment and surgical treatment if it was necessary. It is a follow-up of the patient and their periodontium to anticipate or intercept any recurrence of the disease.',
    'services.paro.surfacage.title': 'Root planing',
    'services.paro.surfacage.desc': 'Root planing is a method of treating periodontitis. It aims to meticulously clean the root surfaces to remove dental plaque and tartar on the root surface, but also inside the periodontal pocket in order to eliminate the bacteria that cause gum disease.',
    'services.esth.title': 'Aesthetic Care',
    'services.esth.q1': 'What is aesthetic dentistry?',
    'services.esth.p1': 'Aesthetic dentistry brings together all dental techniques aimed at improving and restoring the natural beauty of your teeth, enhancing the aesthetic appeal of your smile, while maintaining the health and functionality of your teeth. Aesthetic dentistry can improve your self-image and have a positive physical and psychological impact.',
    'services.esth.q2': 'Why would I need aesthetic dentistry?',
    'services.esth.p2': 'The indications for aesthetic dentistry are numerous and correspond to a large number of clinical situations. The most frequent reasons for aesthetic consultation are:',
    'services.esth.list.item1': 'Replacing one (or more) missing tooth, especially in the anterior sector.',
    'services.esth.list.item2': '“Repairing” a broken, deformed or chipped tooth.',
    'services.esth.list.item3': 'Stained, yellowish, grayish or colored teeth.',
    'services.esth.list.item4': 'The alignment of your smile does not suit you.',
    'services.esth.list.item5': 'Too “gummy” smile (gums are very visible).',
    'services.esth.facettes.title': 'Dental Veneers',
    'services.esth.facettes.desc': 'A dental veneer is a small shell designed in ceramic to cover your existing tooth and mask defects such as unsightly color or poor alignment.',
    'services.esth.couronnes.title': 'All-ceramic crowns',
    'services.esth.couronnes.desc': 'Composed of zirconia and cosmetic ceramic, these crowns without a metal frame offer a high-level aesthetic result and a natural look.',
    'services.esth.inlays.title': 'Inlays-onlays',
    'services.esth.inlays.desc': 'Indirect restoration techniques to replace a large cavity or cover part of the tooth, combining aesthetics and strength.',
    'services.esth.blanchiment.title': 'Teeth Whitening',
    'services.esth.blanchiment.desc': 'Professional tray technique allowing to regain the natural color of the teeth without altering the enamel, for a brighter smile.',
    'services.omni.title': 'General Care',
    'services.omni.p1': 'At MAPSO Dental Center, we perform all general dentistry care to prevent the appearance of cavities, infections, dental pathologies or treat them if they already exist. These treatments are numerous and cover all pathologies of the different structures of your mouth, the most common being dental cavities, tartar management or dental devitalizations.',
    'services.omni.detartrage.title': 'Scaling and polishing',
    'services.omni.detartrage.desc': 'Over time, your mouth naturally produces tartar and its accumulation can lead to the appearance of gingivitis or periodontitis and dull your smile which will lose its radiance. Once formed, tartar can no longer be removed by brushing and you need to perform a scaling session at your dentist. At MAPSO Dental Center, we are equipped with the latest AQUACARE technology which allows for high-quality scaling and polishing.',
    'services.omni.composites.title': 'Dental composites',
    'services.omni.composites.desc': 'Dental composite resin is a white-colored material, very aesthetic since it comes in many shades to best adapt to the natural color of your teeth. It allows for the restoration of anterior and posterior teeth, especially when they have suffered a cavity, a fracture or have a bad position.',
    'services.omni.endodontie.title': 'Endodontic treatments or devitalizations',
    'services.omni.endodontie.desc': 'Root canal treatment consists of removing the internal and living part of the tooth, disinfecting the entire internal canal system, enlarging the main canals and filling them with a filling material to seal them. Your dentist will always advise this type of treatment rather than extraction when possible. Indeed, even devitalized, your tooth performs many functions: chewing, maintaining the position of your teeth and preserving the alveolar bone.',
    'services.proth.title': 'Prosthetic Care',
    'services.proth.p1': 'A dental prosthesis is a dental device replacing one or more missing teeth in order to reshape a complete dental arch.',
    'services.proth.p2': 'Your dental surgeon at the MAPSO dental center in Casablanca has many prosthetic solutions to compensate for tooth loss, rebuild damaged teeth or improve the aesthetics of your smile. The choice will depend on your clinical situation and your expectations.',
    'services.proth.couronne.title': 'Prosthetic crown',
    'services.proth.couronne.desc': 'Dental crowns are fixed prostheses allowing for the reconstruction of damaged, broken or devitalized teeth. A crown will cap your tooth and cover it entirely to solidify it while restoring its aesthetics and chewing potential.',
    'services.proth.bridge.title': 'Dental bridge',
    'services.proth.bridge.desc': 'A bridge is a dental prosthesis that forms a bridge between several teeth to replace one or two missing teeth, resting on the adjacent teeth (pillar teeth). It is a fixed, fast and aesthetic solution.',
    'services.proth.amovible_partielle.title': 'Partial removable dentures',
    'services.proth.amovible_partielle.desc': 'Generally replace several missing teeth. It is partial because it does not replace all teeth and removable because it is not glued. It rests on the gums and adjacent teeth using hooks to restore chewing and the smile.',
    'services.proth.amovible_complete.title': 'Complete removable denture',
    'services.proth.amovible_complete.desc': 'Indicated when there is a total absence of teeth. Often called "dentures", it replaces all the teeth of the top or bottom and can be easily removed. It stays in place by suction effect thanks to saliva.',

    // Footer
    'footer.about': 'Contemporary infrastructure and cutting-edge techniques for excellent dental care in Casablanca.',
    'footer.nav': 'Navigation',
    'footer.contact': 'Contact',
    'footer.rights': 'All rights reserved.',

    // Appointment
    'appointment.tag': 'Appointment Booking',
    'appointment.title': 'Book an Appointment',
    'appointment.form.title': 'Appointment Form',
    'appointment.form.desc': 'Please fill out the form below to request an appointment.',
    'appointment.form.date': 'Preferred Date',
    'appointment.form.time': 'Preferred Time',
    'appointment.form.service': 'Desired Service',
    'appointment.form.submit': 'Confirm Appointment',
  },
  ES: {
    // Header
    'nav.home': 'Inicio',
    'nav.soins': 'Nuestros Cuidados',
    'nav.urgences': 'Urgencias',
    'nav.conseils': 'Consejos',
    'nav.contact': 'Contacto',
    'nav.appointment': 'Pedir Cita',
    'header.location': 'Casablanca, Marruecos',
    'header.subtitle': 'Centro Dental',
    'header.language': 'Idioma',
    
    // Home
    'hero.welcome': 'Bienvenido a MAPSO',
    'hero.title': 'Su Sonrisa, Nuestra Pasión',
    'hero.subtitle': 'Excelencia en el cuidado dental en el corazón de Casablanca',
    'hero.cta': 'Pedir Cita',
    'hero.call': 'Llamar al Gabinete',
    
    'services.title': 'Nuestros Servicios',
    'services.subtitle': 'Una gama completa de cuidados para toda la familia',
    'services.details': 'Ver Detalles',
    'services.more': 'Saber Más',

    'service.omni.title': 'Cuidados Generales',
    'service.omni.desc': 'Realizamos todos los cuidados dentales generales para prevenir la aparición de caries, infecciones...',
    'services.omni.title': 'Cuidados Generales',
    'services.omni.p1': 'En el Centro Dental MAPSO, realizamos todos los cuidados de odontología general para prevenir la aparición de caries, infecciones, patologías dentales o tratarlas si ya existen. Estos tratamientos son numerosos y cubren todas las patologías de las diferentes estructuras de su boca, siendo las más comunes las caries dentales, la gestión del sarro o las desvitalizaciones dentales.',
    'services.omni.detartrage.title': 'Limpieza y pulido',
    'services.omni.detartrage.desc': 'Con el tiempo, su boca produce naturalmente sarro y su acumulación puede provocar la aparición de gingivitis o periodontitis y empañar su sonrisa, que perderá su brillo. Una vez formado, el sarro ya no puede eliminarse mediante el cepillado y es necesario realizar una sesión de limpieza con su dentista. En MAPSO Dental Center, contamos con la última tecnología AQUACARE que permite realizar una limpieza y pulido de calidad.',
    'services.omni.composites.title': 'Composites dentales',
    'services.omni.composites.desc': 'La resina compuesta dental es un material de color blanco, muy estético ya que se presenta en numerosos tonos para adaptarse lo mejor posible al color natural de su dentadura. Permite restaurar los dientes anteriores y posteriores, especialmente cuando han sufrido una caries, una fractura o tienen una mala posición.',
    'services.omni.endodontie.title': 'Tratamientos endodónticos o desvitalizaciones',
    'services.omni.endodontie.desc': 'El tratamiento de conducto consiste en retirar la parte interna y viva del diente, desinfectar todo el sistema de conductos internos, ensanchar los conductos principales y rellenarlos con un material de obturación para sellarlos. Su dentista siempre le aconsejará este tipo de tratamiento en lugar de la extracción cuando sea posible. De hecho, incluso desvitalizado, su diente cumple muchas funciones: masticación, mantenimiento de la posición de sus dientes y preservación del hueso alveolar.',
    'service.ortho.title': 'Ortodoncia',
    'services.ortho.p1': 'Una sonrisa estética y armoniosa es hoy un elemento importante de la vida en sociedad. Si te sientes cohibido por tu sonrisa, encuentras tus dientes mal alineados o tu sonrisa un poco demasiado gingival, la ortodoncia es una solución sencilla y eficaz para mejorar enormemente tu sonrisa y bienestar.',
    'services.ortho.p2': 'Para un niño, el principal desafío es un crecimiento armonioso de los maxilares y un posicionamiento correcto de sus dientes para protegerlo de cualquier perjuicio estético o de oclusión en la edad adulta.',
    'services.ortho.how_title': '¿Cómo funciona un tratamiento de ortodoncia?',
    'services.ortho.how_desc1': 'Los aparatos de ortodoncia están hechos de metal, cerámica o plástico. Pueden ser removibles o fijados a los dientes mediante "brackets". Al ejercer una fuerza suave y constante, mueven lentamente los dientes a la posición correcta.',
    'services.ortho.how_desc2': 'La época de los aparatos exclusivamente metálicos ha terminado; ahora puedes elegir soportes transparentes o metálicos. ¡Hoy en día, cualquier edad es ideal para usar brackets!',
    'services.ortho.duration_title': '¿Cuál es la duración de un tratamiento de ortodoncia?',
    'services.ortho.duration_desc1': 'La duración del tratamiento varía y puede durar entre uno y tres años, dependiendo de varios factores, como la edad, el método de tratamiento y la importancia del tratamiento.',
    'services.ortho.duration_desc2': 'Antes de comenzar su atención de ortodoncia, su ortodoncista discutirá todas las opciones terapéuticas disponibles y le dará una estimación de la duración total de su tratamiento.',
    'services.ortho.invisible.title': 'Ortodoncia Invisible',
    'services.ortho.invisible.desc': 'Existen numerosos tratamientos de ortodoncia invisible que permiten tratar las malposiciones de sus dientes con la mayor discreción.',
    'services.ortho.adult.title': 'Ortodoncia para Adultos',
    'services.ortho.adult.desc': 'En el caso de la ortodoncia para adultos, la elección de su tratamiento estará ligada a sus deseos y necesidades, ya sea un aparato clásico o soluciones más discretas.',
    'services.ortho.invisalign.title': 'Invisalign',
    'services.ortho.invisalign.desc': 'Técnica que utiliza alineadores transparentes e invisibles hechos a medida para alinear los dientes de la manera más discreta posible.',
    'services.ortho.kids.title': 'Ortodoncia para Niños y Adolescentes',
    'services.ortho.kids.desc': 'Dedicada a la prevención y corrección de anomalías de la dentition para asegurar un buen envejecimiento de dientes y encías.',
    'service.esth.title': 'Cuidados Estéticos',
    'service.esth.desc': 'Para embellecer su sonrisa, mejorar y restaurar la belleza natural de sus dientes...',
    'services.esth.title': 'Cuidado Estético',
    'services.esth.q1': '¿Qué es la odontología estética?',
    'services.esth.p1': 'La odontología estética reúne todas las técnicas dentales destinadas a mejorar y restaurar la belleza natural de sus dientes, realzando el atractivo estético de su sonrisa, manteniendo al mismo tiempo la salud y funcionalidad de sus dientes. La odontología estética puede mejorar su imagen personal y tener un impacto físico y psicológico positivo.',
    'services.esth.q2': '¿Por qué necesitaría odontología estética?',
    'services.esth.p2': 'Las indicaciones de la odontología estética son numerosas y corresponden a un gran número de situaciones clínicas. Los motivos más frecuentes de consulta estética son:',
    'services.esth.list.item1': 'Reemplazar uno (o más) dientes faltantes, especialmente en el sector anterior.',
    'services.esth.list.item2': '“Reparar” un diente roto, deformado o astillado.',
    'services.esth.list.item3': 'Dientes manchados, amarillentos, grisáceos o coloreados.',
    'services.esth.list.item4': 'La alineación de su sonrisa no le satisface.',
    'services.esth.list.item5': 'Sonrisa demasiado “gingival” (las encías son muy visibles).',
    'services.esth.facettes.title': 'Carillas Dentales',
    'services.esth.facettes.desc': 'Una carilla dental es una pequeña lámina diseñada en cerámica para cubrir su diente existente y ocultar defectos como un color antiestético o una mala alineación.',
    'services.esth.couronnes.title': 'Coronas totalmente cerámicas',
    'services.esth.couronnes.desc': 'Compuestas de circonio y cerámica cosmética, estas coronas sin estructura metálica ofrecen un resultado estético de alto nivel y un aspecto natural.',
    'services.esth.inlays.title': 'Inlays-onlays',
    'services.esth.inlays.desc': 'Técnicas de restauración indirecta para reemplazar una cavidad grande o cubrir parte del diente, combinando estética y resistencia.',
    'services.esth.blanchiment.title': 'Blanqueamiento Dental',
    'services.esth.blanchiment.desc': 'Técnica profesional mediante férulas que permite recuperar el color natural de los dientes sin alterar el esmalte, para una sonrisa más brillante.',
    'service.paro.title': 'Periodoncia',
    'service.paro.desc': 'Las enfermedades periodontales se deben a infecciones bacterianas. Descubra todos los tratamientos...',
    'services.paro.title': 'Periodoncia',
    'services.paro.p1': 'La periodoncia es la parte de la odontología que se especializa en el tratamiento del periodonto, es decir, los tejidos de soporte del diente: encía, tejido óseo, cemento y ligamento periodontal. Las enfermedades periodontales se deben a infecciones bacterianas.',
    'services.paro.p2': 'Descubra todos los cuidados que brindamos en el centro dental MAPSO en Casablanca, como parte del manejo de sus problemas periodontales.',
    'services.paro.diseases.title': 'Enfermedades periodontales: gingivitis y periodontitis',
    'services.paro.diseases.desc': 'Las enfermedades periodontales son enfermedades y condiciones patológicas que afectan a los tejidos de soporte de los dientes, es decir, el hueso y la encía. La gingivitis y la periodontitis son infecciones causadas por la acumulación de bacterias patógenas y sus toxinas en el borde de la encía alrededor de los dientes y deben ser tratadas para evitar complicaciones.',
    'services.paro.bilan.title': 'Evaluación periodontal',
    'services.paro.bilan.desc': 'Para preservar su capital de salud bucodental, es esencial evaluar y cuidar sus encías. Su dentista realiza esta evaluación a través de un balance periodontal que se desarrolla en varias etapas: interrogatorio médico, análisis clínico, balance radiológico y pruebas bacterianas en algunos casos.',
    'services.paro.maintenance.title': 'Mantenimiento periodontal',
    'services.paro.maintenance.desc': 'El mantenimiento periodontal es la tercera fase del tratamiento de la periodontitis después del tratamiento no quirúrgico y el tratamiento quirúrgico si fue necesario. Se trata de un seguimiento del paciente y su periodonto para anticipar o interceptar cualquier recurrencia de la enfermedad.',
    'services.paro.surfacage.title': 'Alisado radicular',
    'services.paro.surfacage.desc': 'El alisado radicular es un método de tratamiento de la periodontitis. Tiene como objetivo limpiar meticulosamente las superficies radiculares para eliminar la placa dental y el sarro en la superficie de las raíces, pero también dentro de la bolsa periodontal para eliminar las bacterias que causan enfermedades de las encías.',
    'service.proth.title': 'Cuidados Protésicos',
    'service.proth.desc': 'Puede reemplazar uno o más dientes perdidos con un dispositivo dental...',
    'services.proth.title': 'Cuidados Protésicos',
    'services.proth.p1': 'La prótesis dental es un dispositivo dental que reemplaza uno o más dientes ausentes con el fin de reformar una arcada dental completa.',
    'services.proth.p2': 'Su cirujano dentista del centro dental MAPSO en Casablanca dispone de numerosas soluciones protésicas para compensar la pérdida de dientes, reconstruir dientes dañados o mejorar la estética de su sonrisa. La elección dependerá de su situación clínica y de sus expectativas.',
    'services.proth.couronne.title': 'La corona protésica',
    'services.proth.couronne.desc': 'Las coronas dentales son prótesis fijas que permiten reconstruir dientes dañados, rotos o desvitalizados. Una corona cubrirá su diente por completo para solidificarlo y restaurar su estética y potencial masticatorio.',
    'services.proth.bridge.title': 'El puente dental',
    'services.proth.bridge.desc': 'Un puente (bridge) es una prótesis dental que forma un puente entre varios dientes para reemplazar uno o dos dientes faltantes, apoyándose en los dientes adyacentes (dientes pilares). Es una solución fija, rápida y estética.',
    'services.proth.amovible_partielle.title': 'Prótesis removibles parciales',
    'services.proth.amovible_partielle.desc': 'Generalmente reemplazan varios dientes faltantes. Es parcial porque no reemplaza todos los dientes y removible porque no está pegada. Se apoya en las encías y los dientes adyacentes mediante ganchos para restaurar la masticación y la sonrisa.',
    'services.proth.amovible_complete.title': 'La prótesis removible completa',
    'services.proth.amovible_complete.desc': 'Indicada cuando hay una ausencia total de dientes. A menudo llamada "dentadura postiza", reemplaza la totalidad de los dientes superiores o inferiores y se puede quitar fácilmente. Se mantiene en su lugar por efecto de succión gracias a la saliva.',
    'service.impl.title': 'Implantología',
    'service.impl.desc': 'Evite la pérdida de hueso maxilar tras la pérdida de uno o más dientes...',
    'services.implant.title': 'Implantología',
    'services.implant.p1': 'La implantología dental es una rama de la cirugía dental que consiste en colocar implantes en el maxilar superior y/o inferior.',
    'services.implant.p2': 'Esto permite reemplazar los dientes perdidos y abordar problemas estéticos, de estabilidad y de masticación.',
    'services.implant.p3': 'La práctica quirúrgica de la implantología también previene la pérdida de hueso maxilar tras la pérdida de uno o más dientes.',
    'services.implant.pose.title': 'Colocación de Implantes Dentales',
    'services.implant.pose.desc': 'Un implante dental es una raíz artificial, un tornillo de titanio o circonio, colocado en el hueso para reemplazar los dientes perdidos.',
    'services.implant.analysis.title': 'Análisis Pre-implante',
    'services.implant.analysis.desc': 'Antes de cualquier colocación de implantes, se requiere un análisis pre-implante para garantizar la seguridad y el posicionamiento óptimo.',
    'services.implant.greffe.title': 'Injerto Óseo para Implantes',
    'services.implant.greffe.desc': 'Si el volumen óseo es insuficiente, será necesario un injerto óseo para asegurar la durabilidad del implante.',
    'services.implant.sinus.title': 'Elevación de Seno',
    'services.implant.sinus.desc': 'Intervención para rellenar el fondo del seno maxilar con un injerto óseo para permitir la colocación de implantes.',

    'features.team.title': 'Equipo Experimentado',
    'features.team.desc': 'Un equipo profesional y homogéneo a su servicio.',
    'features.human.title': 'Enfoque Humano',
    'features.human.desc': 'Un enfoque humano de la cirugía dental.',
    'features.client.title': 'Servicio al Cliente',
    'features.client.desc': 'Le recibimos con alegría, respondemos a todas sus peticiones.',
    'features.covid.title': 'COVID 19',
    'features.covid.desc': 'Medidas implementadas para protegerle y prevenir la propagación del virus.',
    'features.advice.title': 'Consejos',
    'features.advice.desc': 'Le ofrecemos escucha y asesoramiento personalizado por teléfono.',
    'features.urgency.title': 'Urgencias Dentales',
    'features.urgency.desc': 'Soporte a medida para una gestión óptima de sus urgencias dentales.',

    'about.tag': 'Sobre Nosotros',
    'about.title': 'Su Dentista de Confianza en Casablanca',
    'about.p1': 'Nuestros dentistas en Casablanca Maarif practican muchos servicios que el centro ofrece, tales como: cuidado dental, ortodoncia, implantología, odontopediatría pero también la mejora y reconstrucción de la estética dental y la sonrisa.',
    'about.p2': 'Gracias a herramientas de última generación, nuestro equipo de profesionales puede realizar exámenes completos y minuciosos para garantizarle el mejor resultado.',
    'about.cta': 'Conócenos mejor',

    'quick.urgency.title': 'Urgencias',
    'quick.urgency.desc': 'Atención inmediata',
    'quick.advice.title': 'Consejos',
    'quick.advice.desc': 'Escucha y acompañamiento',
    'quick.find.title': 'Encuéntranos',
    'quick.find.desc': 'En el corazón de Casablanca',

    'cta.title': '¿Necesita información?',
    'cta.subtitle': 'Nuestro equipo está a su disposición para responder a todas sus preguntas.',

    // Urgences
    'urgences.tag': 'Gestión rápida',
    'urgences.title': 'Urgencias Dentales',
    'urgences.intro': 'Accident, infección o trauma... Las urgencias dentales a menudo causan dolor agudo y requieren una intervención rápida.',
    'urgences.availability': 'Disponibilidad inmediata',
    'urgences.hours.title': 'DURANTE EL HORARIO DE APERTURA DEL CENTRO MAPSO',
    'urgences.hours.desc': 'Nuestros dentistas experimentados le dan la bienvenida de lunes a viernes de 9:00 am a 7:00 pm para cualquier emergencia.',
    'urgences.hours.note': 'Póngase en contacto con nuestra secretaría para una gestión prioritaria.',
    'urgences.more': 'Leer más',
    
    'urgences.pain.title': 'Dolor Dental',
    'urgences.pain.desc': 'El dolor dental puede ser insoportable y requerir atención inmediata, especialmente en caso de infección.',
    'urgences.proth.title': 'Urgencias Protésicas',
    'urgences.proth.desc': 'Corona descementada, aparato roto o que lastima... La gestión rápida es esencial para su comodidad.',
    'urgences.paro.title': 'Urgencias Periodontales',
    'urgences.paro.desc': 'Infecciones de las encías, hueso o ligamentos. Estas patologías requieren intervención especializada.',
    'urgences.trauma.title': 'Urgencias Traumáticas',
    'urgences.trauma.desc': 'Traumatismos relacionados con el deporte o accidentes, especialmente frecuentes en niños.',

    // Conseils
    'conseils.tag': 'Higiene y Prevención',
    'conseils.title': 'Nuestros Consejos',
    'conseils.intro1': 'Usted es el principal actor de su salud bucodental. La higiene es fundamental para preservar su sonrisa a lo largo de su vida.',
    'conseils.intro2': 'Los expertos de MAPSO le acompañan en la elección de sus herramientas y técnicas de cepillado.',
    'conseils.expert': 'Consejo de experto',
    'conseils.cta.title': '¿Necesita un chequeo completo?',
    'conseils.cta.desc': 'Pida cita para una consulta de control y reciba asesoramiento personalizado.',
    'conseils.cta.btn': 'Pedir cita',

    'conseils.manual.title': 'Cepillo de dientes manual',
    'conseils.manual.desc': 'El cepillado regular y el uso de hilo dental son esenciales para una buena salud bucodental para prevenir caries.',
    'conseils.mouthwash.title': 'Uso de enjuague bucal',
    'conseils.mouthwash.desc': 'Para asegurar una buena higiene bucodental, la recomendación esencial es cepillarse los dientes dos o tres veces al día.',
    'conseils.electric.title': 'Cepillo de dientes eléctrico',
    'conseils.electric.desc': 'Con un cepillo de dientes recargable, la acción de cepillado es muy diferente porque el propio cepillo proporciona el movimiento necesario.',
    'conseils.floss.title': 'Uso de hilo dental',
    'conseils.floss.desc': 'Si el cepillado es parte integrante de la rutina, el uso de hilo dental es un gesto esencial a menudo descuidado.',

    // Contact
    'contact.tag': 'Contáctenos',
    'contact.title': 'Hablemos de su sonrisa',
    'contact.find.title': 'Encuéntranos',
    'contact.find.content': "Angle Rue Cadi Iass et Rue Saad Bnou Zarara, Imm EL WASSIA, étg 2, n3 Au dessus de McDonald's, Casablanca 20330",
    'contact.call.title': 'Llámanos',
    'contact.call.fix': 'Fijo',
    'contact.email.title': 'Dirección de Email',
    'contact.email.desc': 'Envíanos un mensaje',
    'contact.hours.title': 'Horario de Trabajo',
    'contact.hours.mon_thu': 'Lun - Jue',
    'contact.hours.fri': 'Vie',
    'contact.hours.sat': 'Sáb',
    'contact.form.title': 'Envíanos un mensaje',
    'contact.form.desc': 'Le responderemos lo antes posible.',
    'contact.form.name': 'Su nombre*',
    'contact.form.name_placeholder': 'Juan Pérez',
    'contact.form.email': 'Su email*',
    'contact.form.subject': 'Asunto',
    'contact.form.subject_placeholder': 'Solicitud de información',
    'contact.form.message': 'Su mensaje*',
    'contact.form.message_placeholder': '¿Cómo podemos ayudarle?',
    'contact.form.send': 'Enviar Mensaje',
    'contact.map.cabinet': 'Nuestro Gabinete',
    'contact.map.location': 'Casablanca, Maarif',

    // Footer
    'footer.about': 'Infraestructura contemporánea y técnicas de vanguardia para una excelente atención dental en Casablanca.',
    'footer.nav': 'Navegación',
    'footer.contact': 'Contacto',
    'footer.rights': 'Todos los derechos reservados.',

    // Appointment
    'appointment.tag': 'Reserva de Cita',
    'appointment.title': 'Pedir Cita',
    'appointment.form.title': 'Formulario de Cita',
    'appointment.form.desc': 'Por favor, complete el formulario a continuación para solicitar una cita.',
    'appointment.form.date': 'Fecha deseada',
    'appointment.form.time': 'Hora deseada',
    'appointment.form.service': 'Servicio deseado',
    'appointment.form.submit': 'Confirmar Cita',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('FR');

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  const isRTL = language === 'AR';

  useEffect(() => {
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
    document.documentElement.lang = language.toLowerCase();
  }, [language, isRTL]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      <div className={isRTL ? 'font-arabic' : ''}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
